# .github/workflows/ci.yml - GitHub Actions CI workflow
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        cd backend
        pytest --cov=. --cov-report=xml --cov-report=term

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Run tests with coverage
      run: |
        cd frontend
        npm run test:coverage

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker images
      run: |
        docker compose build

    - name: Check image sizes
      run: |
        docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"

        # Verify total size is under 300MB
        TOTAL_SIZE=$(docker images --format "{{.Size}}" | grep -E '^[0-9]+' | awk '{print $1}' | paste -sd+ | bc)
        echo "Total size: ${TOTAL_SIZE}MB"
        if [ $TOTAL_SIZE -gt 300 ]; then
          echo "Error: Total image size exceeds 300MB"
          exit 1
        fi
